<html>
<head>
<title>TestNG:  Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>8/2/0</td>
</tr><tr>
<td>Started on:</td><td>Thu Oct 04 08:06:41 IST 2018</td>
</tr>
<tr><td>Total time:</td><td>0 seconds (49 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='day6Programming.ExceptionHandlingPractice.accessNewFile()'><b>accessNewFile</b><br>Test class: day6Programming.ExceptionHandlingPractice</td>
<td><div><pre>java.io.FileNotFoundException: D:/Selenium/Practice.html (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:138)
	at java.io.FileReader.&lt;init&gt;(FileReader.java:72)
	at day6Programming.ExceptionHandlingPractice.accessNewFile(ExceptionHandlingPractice.java:21)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace540585569", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace540585569'><pre>java.io.FileNotFoundException: D:/Selenium/Practice.html (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:138)
	at java.io.FileReader.&lt;init&gt;(FileReader.java:72)
	at day6Programming.ExceptionHandlingPractice.accessNewFile(ExceptionHandlingPractice.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>day6Programming.ExceptionHandlingPractice@7ac7a4e4</td></tr>
<tr>
<td title='day6Programming.ExceptionHandlingPractice.newExceptionThrown()'><b>newExceptionThrown</b><br>Test class: day6Programming.ExceptionHandlingPractice</td>
<td><div><pre>java.lang.Exception: This is my own created exception, and it is displayed whenever i need
	at day6Programming.ExceptionHandlingPractice.newExceptionThrown(ExceptionHandlingPractice.java:30)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace836514715", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace836514715'><pre>java.lang.Exception: This is my own created exception, and it is displayed whenever i need
	at day6Programming.ExceptionHandlingPractice.newExceptionThrown(ExceptionHandlingPractice.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>day6Programming.ExceptionHandlingPractice@7ac7a4e4</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='day3Programming.OperatorsPractcie.arithmeticOperations()'><b>arithmeticOperations</b><br>Test class: day3Programming.OperatorsPractcie</td>
<td></td>
<td>0</td>
<td>day3Programming.OperatorsPractcie@402f32ff</td></tr>
<tr>
<td title='day3Programming.OperatorsPractcie.assignmentOperations()'><b>assignmentOperations</b><br>Test class: day3Programming.OperatorsPractcie</td>
<td></td>
<td>0</td>
<td>day3Programming.OperatorsPractcie@402f32ff</td></tr>
<tr>
<td title='day4Programming.SwitchStatementExample.calculator()'><b>calculator</b><br>Test class: day4Programming.SwitchStatementExample</td>
<td></td>
<td>0</td>
<td>day4Programming.SwitchStatementExample@6d8a00e3</td></tr>
<tr>
<td title='day5Programming.StringPractice.fetchNamesFromEmailIDs()'><b>fetchNamesFromEmailIDs</b><br>Test class: day5Programming.StringPractice</td>
<td></td>
<td>0</td>
<td>day5Programming.StringPractice@548b7f67</td></tr>
<tr>
<td title='day3Programming.OperatorsPractcie.logicalOperations()'><b>logicalOperations</b><br>Test class: day3Programming.OperatorsPractcie</td>
<td></td>
<td>0</td>
<td>day3Programming.OperatorsPractcie@402f32ff</td></tr>
<tr>
<td title='day3Programming.OperatorsPractcie.relationOperations()'><b>relationOperations</b><br>Test class: day3Programming.OperatorsPractcie</td>
<td></td>
<td>0</td>
<td>day3Programming.OperatorsPractcie@402f32ff</td></tr>
<tr>
<td title='day5Programming.StringPractice.stringExample()'><b>stringExample</b><br>Test class: day5Programming.StringPractice</td>
<td></td>
<td>0</td>
<td>day5Programming.StringPractice@548b7f67</td></tr>
<tr>
<td title='day6Programming.ExceptionHandlingPractice.tryCatchExceptionExample()'><b>tryCatchExceptionExample</b><br>Test class: day6Programming.ExceptionHandlingPractice</td>
<td></td>
<td>0</td>
<td>day6Programming.ExceptionHandlingPractice@7ac7a4e4</td></tr>
</table><p>
</body>
</html>