<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="f45c899d4237" ignored="0" name="Test" tests="10" failures="2" timestamp="04 Oct 2018 02:36:41 GMT" time="0.049" errors="0">
  <testcase name="arithmeticOperations" time="0.009" classname="day3Programming.OperatorsPractcie"/>
  <testcase name="assignmentOperations" time="0.001" classname="day3Programming.OperatorsPractcie"/>
  <testcase name="logicalOperations" time="0.001" classname="day3Programming.OperatorsPractcie"/>
  <testcase name="relationOperations" time="0.001" classname="day3Programming.OperatorsPractcie"/>
  <testcase name="calculator" time="0.001" classname="day4Programming.SwitchStatementExample"/>
  <testcase name="fetchNamesFromEmailIDs" time="0.002" classname="day5Programming.StringPractice"/>
  <testcase name="stringExample" time="0.002" classname="day5Programming.StringPractice"/>
  <testcase name="accessNewFile" time="0.001" classname="day6Programming.ExceptionHandlingPractice">
    <failure type="java.io.FileNotFoundException" message="D:/Selenium/Practice.html (No such file or directory)">
      <![CDATA[java.io.FileNotFoundException: D:/Selenium/Practice.html (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at day6Programming.ExceptionHandlingPractice.accessNewFile(ExceptionHandlingPractice.java:21)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- accessNewFile -->
  <testcase name="newExceptionThrown" time="0.001" classname="day6Programming.ExceptionHandlingPractice">
    <failure type="java.lang.Exception" message="This is my own created exception, and it is displayed whenever i need">
      <![CDATA[java.lang.Exception: This is my own created exception, and it is displayed whenever i need
	at day6Programming.ExceptionHandlingPractice.newExceptionThrown(ExceptionHandlingPractice.java:30)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- newExceptionThrown -->
  <testcase name="tryCatchExceptionExample" time="0.001" classname="day6Programming.ExceptionHandlingPractice"/>
</testsuite> <!-- Test -->
